server:
  port: 8081

spring:
  application:
    name: kafka-consumer-dev
  kafka:
    bootstrap-servers: my-kafka-kafka-brokers.kafka.svc.cluster.local:9092
    consumer:
      group-id: dev-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1000
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="dev-user" password="eOh7XwTuu5xGe0ql82NLJyEW2450GXOg";

kafka:
  topic:
    name: dev.xyz

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,kafka
  endpoint:
    health:
      show-details: always